site_name: T1nk3r
theme:
  name: material
#  custom_dir: overrides
  font:
    text: Manrope
  icon:
    logo: octicons/terminal-16
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - header.autohide
    - announce.dismiss
  language: en
  palette: 
    - scheme: default
      toggle: 
        icon: material/toggle-switch-off
        name: Switch to dark mode
      primary: black 
      accent: amber
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: amber
      accent: yellow

# Plugins here
plugins: 
  - search

# Markdown Extensions
markdown_extensions: 
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Extra CSS File
extra_css:
  - stylesheets/extra.css

# Footer details
extra: 
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/1zyik
    - icon: fontawesome/brands/youtube
      link: https://github.com/1zyik
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/isaac-cloudengineer/
  # Cookies block for consent
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

copyright: |
  &copy; 2025 <a href="https://github.com/1zyik" target="_blank" rel="noopener">Isaac Adepitan</a> 

# Navigation Setup
nav:
  - Knowledge Base: 
      - 'Welcome':
        - 'Welcome': index.md
      - 'Scripting':
        - 'Bash': sections/scripting/bash.md
        - 'Command Prompt': sections/scripting/cmd-prompt.md
        - 'Powershell': sections/scripting/powershell.md
        - 'Python': sections/scripting/python.md
      - 'DevOps':
        - 'ArgoCD': sections/devops/argocd.md
        - 'AWS':
          - 'IAM Policies': sections/devops/iam-policies/iam-policies.md
        - 'Azure': sections/devops/azure.md
        - 'Docker': sections/devops/docker.md
      - 'SRE':
        - 'Azure Monitor': sections/sre/azure-monitor.md
      - 'CLI Utilities':
        - 'aws-cli': sections/utilities/aws-cli.md
        - 'eksctl': sections/utilities/eksctl.md
        - 'git': sections/utilities/git.md         
        - 'gpg': sections/utilities/gpg.md
        - 'kubectl': sections/utilities/kubectl.md
      - 'Linux':
        - 'Ubuntu': sections/linux/ubuntu.md